# Site settings
title: YZi's Photo Journal
email: ""
description: "YZi's Photo Journal"
url: "https://weirdkittyz.github.io"
baseurl: "/YZiPhotoJournal"


instagram_username: "z._4869"
github_username:  "WeirdKittyZ"
email: "zyjzjq99@sina.com"
share: true

# Owner/author information
owner:
  name:   YZi
  favicon: favicon.ico
  info: YZi's Photo Journal

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY I: "https://weirdkittyz.github.io/YZiPhotoJournal/gallery/" 
  - GALLERY II: "https://weirdkittyz.github.io/YZiPhotoJournal/galleryII/"
  - GALLERY III: "https://weirdkittyz.github.io/YZiPhotoJournal/galleryIII/"
  - ABOUT: "https://weirdkittyz.github.io/YZiPhotoJournal/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings (journal)
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

